# 服务配置
server:
  host: "localhost"
  port: 3000
env:
  NODE_ENV: "development"
db:  
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "你的密码"
  database: "你的数据库名字"
  synchronize: true
  logging: true
redis:
  host: "localhost"
  port: 6379
  enableAuth: false
swagger:
  enable: true
jwt:
  secret: "zero"
  expireIn: '7d' #表示过期时间7天
logger:
  level: 'debug'